### ISSUE TITLE
Keep only data for requested model year

### ISSUE THREAD

**Issue by brynpickering** [timtroendle/euro-calliope#23]
The biggest memory hog in the built models is the timeseries data. Since the model is built for a specific year, only that year of data should be kept in *all* timeseries datasets. 

From what I can tell, PV and wind timeseries data covers the full time range of the data accessed from renewables.ninja (2000-2016?). This should be cut to just the model year of interest, which would decrease their disk usage by a factor of 10.

**Comment by timtroendle** [comment]
I agree with you that there is something odd here. The disadvantage of your approach is that it makes running the pre-built model for another year even more difficult (or impossible). But maybe that's a disadvantage that one has to accept when using pre-built models.

As this would be a breaking change, I propose to add it with a new config flag: `keep-all-ninja-data` or something like that so that one can omit the new behaviour.

**Comment by brynpickering** [comment]
Well, you already can't run for another year since the demand and hydro data is only given for the year of choice. This is more about stripping out the weather data that doesn't match with the other datasets, so I don't see it as breaking...

**Comment by timtroendle** [comment]
It's breaking because I am using it. ;-) I am using it with all other data fixed to 2016.

**Comment by brynpickering** [comment]
:O

Fair enough, adding with a flag seems like a reasonable compromise.
